name: CI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Check formatting
        run: cd packages/contracts && yarn run formatting:check
      - name: Compile
        run: cd packages/contracts && yarn run build && yarn run build:npm
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
        run: cd packages/contracts && yarn run test
      - name: Run solidity-docgen
        run: cd packages/contracts && yarn run docgen

      - name: Copy env of Validator
        run: cp packages/validator/env/.env.sample packages/validator/env/.env
      - name: Check formatting of Validator
        run: cd packages/validator && yarn run formatting:check
      - name: Compile of Validator
        run: cd packages/validator && yarn run build
      - name: Run Hardhat Tests of Validator
        run: cd packages/validator && yarn run test
